const BOARDS = [
  {
    id: 'LotusDevkit',
    name: 'LotusDevkit',
    title: 'Lotus Devkit',
    description: 'บอร์ดการเรียนรู้หุ่นยนต์และโครงงาน IoT',
    platform: 'arduino-esp32',
    fqbn: 'esp32:esp32:esp32',
    uploadProtocol: 'esptool',
    baudrate: 921600,
    image: '/boards/LotusDevkit/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'LotusDevkit4Wheels',
    name: 'LotusDevkit4Wheels',
    title: 'Lotus Devkit 4 Wheels',
    description: 'บอร์ดหุ่นยนต์ 4 ล้อ (ESP32)',
    platform: 'arduino-esp32',
    fqbn: 'esp32:esp32:esp32',
    uploadProtocol: 'esptool',
    baudrate: 921600,
    image: '/boards/LotusDevkit4Wheels/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'LotusMegaBot',
    name: 'LotusMegaBot',
    title: 'Lotus MegaBot',
    description: 'บอร์ดหุ่นยนต์ Arduino Mega',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    image: '/boards/LotusMegaBot/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'LotusMegaBotPlus',
    name: 'LotusMegaBotPlus',
    title: 'Lotus MegaBot Plus',
    description: 'บอร์ดหุ่นยนต์ Arduino Mega Plus',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    image: '/boards/LotusMegaBotPlus/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'LotusNanoBot',
    name: 'LotusNanoBot',
    title: 'Lotus NanoBot',
    description: 'บอร์ดหุ่นยนต์ Arduino Nano',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:nano:cpu=atmega328old',
    uploadProtocol: 'arduino',
    baudrate: 57600,
    image: '/boards/LotusNanoBot/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'LotusDueBot',
    name: 'LotusDueBot',
    title: 'Lotus DueBot',
    description: 'บอร์ดหุ่นยนต์ Arduino DUE (ARM)',
    platform: 'arduino-sam',
    fqbn: 'arduino:sam:arduino_due_x_dbg',
    uploadProtocol: 'sam-ba',
    baudrate: 115200,
    touchBaudrate: 1200,
    image: '/boards/LotusDueBot/display.jpg',
    group: 'Lotus',
  },
  {
    id: 'arduino-uno',
    name: 'arduino-uno',
    title: 'Arduino Uno',
    description: 'Arduino Uno R3 (ATmega328P)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:uno',
    uploadProtocol: 'arduino',
    baudrate: 115200,
    image: '/boards/arduino-uno/display.jpg',
    group: 'Arduino',
  },
  {
    id: 'arduino-nano',
    name: 'arduino-nano',
    title: 'Arduino Nano',
    description: 'Arduino Nano (ATmega328P old bootloader)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:nano:cpu=atmega328old',
    uploadProtocol: 'arduino',
    baudrate: 57600,
    image: '/boards/arduino-nano/display.jpg',
    group: 'Arduino',
  },
  {
    id: 'arduino-mega',
    name: 'arduino-mega',
    title: 'Arduino Mega',
    description: 'Arduino Mega 2560 (ATmega2560)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    image: '/boards/arduino-mega/display.jpg',
    group: 'Arduino',
  },
  {
    id: 'kidbright-arduino',
    name: 'kidbright-arduino',
    title: 'KidBright (Arduino mode)',
    description: 'KidBright บอร์ด ESP32 โหมด Arduino',
    platform: 'arduino-esp32',
    fqbn: 'esp32:esp32:esp32',
    uploadProtocol: 'esptool',
    baudrate: 921600,
    image: '/boards/kidbright-arduino/display.jpg',
    group: 'KidBright',
  },
]

module.exports = { BOARDS }
