export const BOARDS = [
  {
    id: 'LotusDevkit',
    name: 'LotusDevkit',
    title: 'Lotus Devkit',
    description: 'Learning robotics and IoT project board (ESP32)',
    platform: 'arduino-esp32',
    fqbn: 'esp32:esp32:esp32',
    uploadProtocol: 'esptool',
    baudrate: 921600,
    group: 'Lotus',
    image: 'boards/LotusDevkit/static/display.jpg',
  },
  {
    id: 'LotusDevkit4Wheels',
    name: 'LotusDevkit4Wheels',
    title: 'Lotus Devkit 4 Wheels',
    description: '4-Wheel robot board (ESP32)',
    platform: 'arduino-esp32',
    fqbn: 'esp32:esp32:esp32',
    uploadProtocol: 'esptool',
    baudrate: 921600,
    group: 'Lotus',
    image: 'boards/LotusDevkit4Wheels/static/display.jpg',
  },
  {
    id: 'LotusMegaBot',
    name: 'LotusMegaBot',
    title: 'Lotus MegaBot',
    description: 'Mega robot board (ATmega2560)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    group: 'Lotus',
    image: 'boards/LotusMegaBot/static/display.jpg',
  },
  {
    id: 'LotusMegaBotPlus',
    name: 'LotusMegaBotPlus',
    title: 'Lotus MegaBot Plus',
    description: 'Mega Plus robot board (ATmega2560)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    group: 'Lotus',
    image: 'boards/LotusMegaBotPlus/static/display.jpg',
  },
  {
    id: 'LotusNanoBot',
    name: 'LotusNanoBot',
    title: 'Lotus NanoBot',
    description: 'Nano robot board (ATmega328P)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:nano:cpu=atmega328old',
    uploadProtocol: 'arduino',
    baudrate: 57600,
    group: 'Lotus',
    image: 'boards/LotusNanoBot/static/display.jpg',
  },
  {
    id: 'LotusDueBot',
    name: 'LotusDueBot',
    title: 'Lotus DueBot',
    description: 'DUE robot board (ARM Cortex-M3)',
    platform: 'arduino-sam',
    fqbn: 'arduino:sam:arduino_due_x_dbg',
    uploadProtocol: 'sam-ba',
    baudrate: 115200,
    touchBaudrate: 1200,
    group: 'Lotus',
    image: 'boards/LotusDueBot/static/display.jpg',
  },
  {
    id: 'arduino-uno',
    name: 'arduino-uno',
    title: 'Arduino Uno',
    description: 'Arduino Uno R3 (ATmega328P)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:uno',
    uploadProtocol: 'arduino',
    baudrate: 115200,
    group: 'Arduino',
    image: 'boards/arduino-uno/static/display.jpg',
  },
  {
    id: 'arduino-nano',
    name: 'arduino-nano',
    title: 'Arduino Nano',
    description: 'Arduino Nano (ATmega328P old bootloader)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:nano:cpu=atmega328old',
    uploadProtocol: 'arduino',
    baudrate: 57600,
    group: 'Arduino',
    image: 'boards/arduino-nano/static/display.jpg',
  },
  {
    id: 'arduino-mega',
    name: 'arduino-mega',
    title: 'Arduino Mega',
    description: 'Arduino Mega 2560 (ATmega2560)',
    platform: 'arduino-avr',
    fqbn: 'arduino:avr:mega:cpu=atmega2560',
    uploadProtocol: 'wiring',
    baudrate: 115200,
    group: 'Arduino',
    image: 'boards/arduino-mega/static/display.jpg',
  },
]

